# Generated by Django 5.2.6 on 2025-10-25 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=30)),
                ("slug", models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=30)),
                ("description_courte", models.CharField(max_length=50)),
                ("description_complete", models.TextField()),
                ("date_debut", models.DateTimeField()),
                ("date_fin", models.DateTimeField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("lien_inscription", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Membre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_complet", models.CharField(max_length=40)),
                ("role", models.CharField(max_length=30)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "photo_profil",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("pays_origine", models.CharField()),
                ("ordre_affichage", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ParametreSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cle", models.CharField(max_length=30)),
                ("valeur", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=30)),
                ("description_courte", models.CharField(max_length=50)),
                ("description_complete", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("lien_demo", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=30)),
                ("slug", models.SlugField()),
                ("contenu", models.TextField()),
                ("date_publication", models.DateTimeField()),
                ("est_publie", models.BooleanField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "auteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.categoriearticle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompteRendu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=30)),
                ("contenu", models.TextField()),
                ("fichier_pdf", models.FileField(blank=True, null=True, upload_to="")),
                ("date_creation", models.DateTimeField()),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.evenement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Partenariat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=30)),
                ("logo", models.URLField()),
                ("description", models.CharField()),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.parametresite",
                    ),
                ),
            ],
        ),
    ]
